export const MosaicConstants = {

    NUM_IMAGES_SETTING: 'NUM_IMAGES_SETTING',
    MIN_NUM_IMAGES: 10,
    MAX_NUM_IMAGES: 200,

    TILING_IMAGE_SCALE_SETTING: 'TILING_IMAGE_SCALE_SETTING',
    MIN_TILING_IMAGE_SCALE: 10,
    MAX_TILING_IMAGE_SCALE: 300,

    OUTPUT_IMAGE_SCALE_SETTING: 'OUTPUT_IMAGE_SCALE_SETTING',
    MIN_OUTPUT_IMAGE_SCALE: 0.25,
    MAX_OUTPUT_IMAGE_SCALE: 4.0,
    STEP_OUTPUT_IMAGE_SCALE: 0.1,

};